-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
        # Trims trailing whitespace
    -   id: trailing-whitespace
        # Ensures files end in newline character
    -   id: end-of-file-fixer
        exclude: boomerrang/static/
        # Auto-formats python code
    -   id: autopep8-wrapper
        # Prevent large (>500kb default) files from being committed
    -   id: check-added-large-files
        # Checks basic yaml syntax
    -   id: check-yaml
        # Checks for debug statements in code
    -   id: debug-statements
        # Makes sure django test files in tests/ are names properly
    -   id: name-tests-test
        args: ['--django']
        # Makes sure entries are sorted
    -   id: requirements-txt-fixer
        # Runs flake8 over python code
    -   id: flake8
        # Don't accidentally import debugger
    -   id: debug-statements

-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
        # Sorts the order of imports
      - id: python-import-sorter
        args: ['--silent-overwrite']
