repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
        exclude: boomerrang/static/
    -   id: end-of-file-fixer
        exclude: boomerrang/static/
    -   id: autopep8-wrapper
    -   id: check-added-large-files
        exclude: boomerrang/static/
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        args:
        - --django
    -   id: requirements-txt-fixer
    -   id: flake8
    -   id: debug-statements
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
