# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField()),
                ('success', models.NullBooleanField()),
                ('duration', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')])),
                ('target_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')])),
                ('call_completed', models.NullBooleanField()),
                ('time_scheduled', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='callrequest',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='boomerrang_app.Org'),
        ),
        migrations.AddField(
            model_name='call',
            name='call_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='boomerrang_app.CallRequest'),
        ),
    ]
