# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boomerrang_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='boomerrang_app.CallRequest'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_requests', to='boomerrang_app.Org'),
        ),
    ]
