# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomerrang_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
        migrations.AlterUniqueTogether(
            name='callrequest',
            unique_together=set([('source_num', 'target_num', 'time_scheduled', 'call_completed', 'org')]),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
